### ISSUE TITLE
Detalles de SEO

### ISSUE THREAD

**Issue by mascam97** [gerardogaravito/gera_web#1]
Agrega la etiqueta meta de description y si es posible Open Graph protocol para redes sociales.
Cuida que tus demás redes sociales también tengan el link a tu sitio web. 
Todo esto con el fin de que tu sitio empiece a tener mejor posición en buscadores cuando busquen en Google https://www.google.com/search?q=gerardogaravito, también aparezca tu sitio web y no solo tu perfil de LinkedIn, Platzi, etc.

**Comment by gerardogaravito** [comment]
Done. Agregué open graph y NextSeo, gracias por el review!
